name: Max Gilmour
markdown: kramdown
baseurl: /
url: http://maxgmr.github.io
collections:
  projects:
    output: true
sass:
  sass_dir: _sass
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
